name: WorkflowEvents

on: 
  schedule:
    - cron: '38 22 * * *' 
      timezone: Europe/Lisbon
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "This workflow's trigger event is: ${{ github.event_name }}"
